"""add catalog tables

Revision ID: 0004_catalog
Revises: 0003_sessions
Created: phase 4, catalog

Reviewed by hand. Three new tables, no data to lose, no renames.

Two partial indexes worth noting:
  ix_contract_templates_category_id_published — the catalog only ever reads
    published rows, so the index only covers them.
  uq_template_versions_one_current — a partial UNIQUE is the only way to say
    "at most one current version per template". A plain unique on
    (template_id, is_current) would also forbid two superseded versions, which
    is the normal case.


Read this before committing it. Autogenerate infers intent from a schema diff
and infers imperfectly — a rename usually comes out as a drop plus an add,
which is data loss wearing a convincing costume.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0004_catalog'
down_revision: str | None = '0003_sessions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('contract_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_bani', sa.BigInteger(), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cardinality(languages) > 0', name=op.f('ck_contract_templates_languages_not_empty')),
    sa.CheckConstraint('price_bani > 0', name=op.f('ck_contract_templates_price_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_contract_templates_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_templates')),
    sa.UniqueConstraint('slug', name=op.f('uq_contract_templates_slug'))
    )
    op.create_index('ix_contract_templates_category_id_published', 'contract_templates', ['category_id'], unique=False, postgresql_where=sa.text('is_published'))
    op.create_table('template_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('docx_object_key', sa.String(length=500), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_template_versions_version_positive')),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], name=op.f('fk_template_versions_template_id_contract_templates')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_template_versions_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_versions')),
    sa.UniqueConstraint('template_id', 'version', name='uq_template_versions_template_id_version')
    )
    op.create_index('uq_template_versions_one_current', 'template_versions', ['template_id'], unique=True, postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_template_versions_one_current', table_name='template_versions', postgresql_where=sa.text('is_current'))
    op.drop_table('template_versions')
    op.drop_index('ix_contract_templates_category_id_published', table_name='contract_templates', postgresql_where=sa.text('is_published'))
    op.drop_table('contract_templates')
    op.drop_table('categories')
    # ### end Alembic commands ###
