"""add wallet tables

Revision ID: b39ca587fc1e
Revises: 0004_catalog
Created: 2026-07-17 13:57:32.936963

Read this before committing it. Autogenerate infers intent from a schema diff
and infers imperfectly — a rename usually comes out as a drop plus an add,
which is data loss wearing a convincing costume.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0005_wallet'
down_revision: str | None = '0004_catalog'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_cards',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_token', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=20), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('exp_month BETWEEN 1 AND 12', name=op.f('ck_payment_cards_exp_month_valid')),
    sa.CheckConstraint('length(last4) = 4', name=op.f('ck_payment_cards_last4_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_cards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_cards'))
    )
    op.create_index('ix_payment_cards_user_id', 'payment_cards', ['user_id'], unique=False)
    op.create_index('uq_payment_cards_one_default', 'payment_cards', ['user_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_bani', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('provider_charge_id', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint("kind IN ('topup', 'purchase', 'refund', 'adjustment')", name=op.f('ck_wallet_transactions_kind_valid')),
    sa.CheckConstraint('amount_bani <> 0', name=op.f('ck_wallet_transactions_amount_not_zero')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallet_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_transactions'))
    )
    op.create_index('ix_wallet_transactions_user_id_created_at', 'wallet_transactions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallet_transactions_user_id_created_at', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index('uq_payment_cards_one_default', table_name='payment_cards', postgresql_where=sa.text('is_default'))
    op.drop_index('ix_payment_cards_user_id', table_name='payment_cards')
    op.drop_table('payment_cards')
    # ### end Alembic commands ###
