"""add cart and order tables

Revision ID: 2819b36d0859
Revises: 0005_wallet
Created: 2026-07-17 18:01:50.368429

Read this before committing it. Autogenerate infers intent from a schema diff
and infers imperfectly — a rename usually comes out as a drop plus an add,
which is data loss wearing a convincing costume.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0006_orders'
down_revision: str | None = '0005_wallet'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Order numbers are drawn from this sequence: CT-{year}-{nextval}. Not a
    # model, so autogenerate does not see it and the test harness creates it
    # separately after create_all. Gaps are expected and fine — see
    # docs/data-model.md and app/models/order.py.
    op.execute("CREATE SEQUENCE order_number_seq")
    op.create_table('carts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts')),
    sa.UniqueConstraint('user_id', name=op.f('uq_carts_user_id'))
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_bani', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("payment_method IN ('wallet', 'card')", name=op.f('ck_orders_payment_method_valid')),
    sa.CheckConstraint("status IN ('pending', 'paid', 'failed', 'cancelled')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('total_bani >= 0', name=op.f('ck_orders_total_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('number', name=op.f('uq_orders_number'))
    )
    op.create_index('ix_orders_user_id_created_at', 'orders', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], name=op.f('fk_cart_items_template_id_contract_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items')),
    sa.UniqueConstraint('cart_id', 'template_id', name='uq_cart_items_cart_id_template_id')
    )
    op.create_index('ix_cart_items_cart_id', 'cart_items', ['cart_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_version_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.Text(), nullable=False),
    sa.Column('unit_price_bani', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('unit_price_bani >= 0', name=op.f('ck_order_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], name=op.f('fk_order_items_template_id_contract_templates')),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], name=op.f('fk_order_items_template_version_id_template_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_cart_items_cart_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('ix_orders_user_id_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_table('carts')
    op.execute("DROP SEQUENCE order_number_seq")
    # ### end Alembic commands ###
