"""add companies table

Revision ID: 5e25c08eec11
Revises: 0006_orders
Created: 2026-07-17 18:39:40.676608

Read this before committing it. Autogenerate infers intent from a schema diff
and infers imperfectly — a rename usually comes out as a drop plus an add,
which is data loss wearing a convincing costume.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0007_companies'
down_revision: str | None = '0006_orders'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('idno', sa.String(length=13), nullable=False),
    sa.Column('legal_address', sa.Text(), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(idno) = 13', name=op.f('ck_companies_idno_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_companies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('user_id', name=op.f('uq_companies_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
